---
name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Build and package
        uses: a-light-win/builder@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          zig_project: "{{ github.workspace }}"
